- hosts: tomcat
  become: yes
  tasks:
    - name: Установка Java
      apt:
        name: openjdk-17-jdk
        state: present

#    - name: Копировать .war файл на сервер
#      copy:
#        src: demo-0.0.1-SNAPSHOT.war  # Замените на путь к вашему .war файлу
#        dest: /opt/tomcat/webapps/demo-0.0.1-SNAPSHOT.war

    - name: Копирование WAR файла в временную директорию
      copy:
        src: demo-0.0.1-SNAPSHOT.war  # Путь к вашему WAR файлу
        dest: /tmp/demo-0.0.1-SNAPSHOT.war

    - name: Создание директории для развертывания
      file:
        path: /opt/tomcat/webapps/demo-0.0.1-SNAPSHOT
        state: directory
#        owner: tomcat
#        group: tomcat
        mode: '755'

    - name: Разархивирование WAR файла
      unarchive:
        src: /tmp/demo-0.0.1-SNAPSHOT.war  # Путь к временной директории
        dest: /opt/tomcat/webapps/demo-0.0.1-SNAPSHOT  # Путь к вашей директории webapps
        remote_src: yes  # Указывает, что исходный файл уже находится на удалённой машине
#    - name: Установка прав доступа к разархивированной папке
#      file:
#        path: /opt/tomcat/webapps/demo-0.0.1-SNAPSHOT
#        owner: tomcat
#        group: tomcat
#        mode: '755'
#        state: directory

#        src: demo-0.0.1-SNAPSHOT.war  # Замените на путь к вашему .war файлу
#        dest: /opt/tomcat/webapps/demo-0.0.1-SNAPSHOT.war

    - name: Перезапуск Tomcat
      shell: /opt/tomcat/bin/shutdown.sh && /opt/tomcat/bin/startup.sh

    - name: Send notification email
      mail:
        host: smtp.gmail.com  # Настройте SMTP-сервер
        port: 587
        username: "{{ lookup('env', 'SMTP_USERNAME') }}"    # Используйте секрет для имени пользователя
        password: "{{ lookup('env', 'SMTP_PASSWORD') }}"    # Используйте секрет для пароля
#        to: ccentre@inbox.ru
        to: serega_baranov_2017@mail.ru
        subject: Application deployed successfully!
        body: Приложение успешно развернуто на вашем сервере Tomcat (The app has been successfully deployed on Tomcat.)
