- hosts: tomcat
  become: yes
  tasks:
    - name: Установка Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Копировать .war файл на сервер
      copy:
        src: demo-0.0.1-SNAPSHOT.war  # Замените на путь к вашему .war файлу
        dest: /opt/tomcat/webapps/demo-0.0.1-SNAPSHOT.war

    - name: Запуск Tomcat
      shell: /opt/tomcat/bin/.shutdown.sh
      shell: /opt/tomcat/bin/.startup.sh

    - name: Send notification email
      mail:
        host: smtp.gmail.com  # Настройте SMTP-сервер
        port: 587
        username: "{{ lookup('env', 'SMTP_USERNAME') }}"    # Используйте секрет для имени пользователя
        password: "{{ lookup('env', 'SMTP_PASSWORD') }}"    # Используйте секрет для пароля
#        to: ccentre@inbox.ru
        to: serega_baranov_2017@mail.ru
        subject: Application deployed successfully!
        body: Приложение успешно развернуто на вашем сервере Tomcat (The app has been successfully deployed on Tomcat.)
