name: Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Download WAR file
#      run: |
#        wget https://github.com/12sergey12/pipeline/blob/main/target/demo-0.0.1-SNAPSHOT.war  # укажите правильный путь

    - name: Клонирование репозитория из GitHub
      run: |
        git clone https://github.com/12sergey12/pipeline.git /tmp/pipeline

    - name: Setup Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 94.130.98.86 >> ~/.ssh/known_hosts

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.MY_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: false  # Отключение проверки SSH ключа во время тестирования
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: ansible-playbook -i inventory.ini deploy.yml








